// ⚠️  Auto-generated by scripts/apply-branding.mjs — do not edit directly.
// To update branding, edit app.config.mjs and run: pnpm run brand

export const APP_NAME           = '喵哥Claw'
export const APP_ID             = 'com.miaoge.claw.desktop'
export const FIREWALL_RULE_NAME = '喵哥Claw'
